### ISSUE TITLE
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

### ISSUE THREAD

**Issue by cristianmtr** [peterjc/flake8-rst-docstrings#31]
Is 3.8 supported? Tried to run this on Python 3.8 but I got the following:

```
/home/cristian/.local/lib/python3.8/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/checker.py", line 648, in _run_checks
    return checker.run_checks()
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/checker.py", line 486, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/checker.py", line 435, in run_check
    return plugin['plugin'](**arguments)
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/plugins/pyflakes.py", line 90, in __init__
    super(FlakesChecker, self).__init__(tree, filename,
  File "/home/cristian/.local/lib/python3.8/site-packages/pyflakes/checker.py", line 494, in __init__
    self.handleChildren(tree)
  File "/home/cristian/.local/lib/python3.8/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/cristian/.local/lib/python3.8/site-packages/pyflakes/checker.py", line 863, in handleNode
    handler(node)
  File "/home/cristian/.local/lib/python3.8/site-packages/pyflakes/checker.py", line 816, in handleChildren
    self.handleNode(node, tree)
  File "/home/cristian/.local/lib/python3.8/site-packages/pyflakes/checker.py", line 862, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/home/cristian/.local/lib/python3.8/site-packages/pyflakes/checker.py", line 696, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cristian/.local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/checker.py", line 319, in run
    self.run_parallel()
  File "/home/cristian/.local/lib/python3.8/site-packages/flake8/checker.py", line 288, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

```

**Comment by peterjc** [comment]
Python 3.8 for ``flake8-rst-docstrings`` should be fine, here's the most recent TravisCI run:

https://travis-ci.org/github/peterjc/flake8-rst-docstrings/jobs/730893924

Have you accidentally filed this issue on the wrong repository? From the tracebacks I would think your flake8/pyflakes is to blame - most likely https://github.com/PyCQA/pyflakes/issues/367 which has been fixed. Try updating flake8 and its dependencies?

**Comment by cristianmtr** [comment]
You are right.

I initially thought that I had updated flake8, but apparently the `pip` directory source does not include the fix. Had to install from git.

Thanks! 

Closing
